#############################################################################
# Makefile for building: hw4
# Generated by qmake (2.01a) (Qt 4.6.2) on: Wed Apr 25 20:04:17 2012
# Project:  hw4.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile hw4.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bomb.cpp \
		bounds.cpp \
		bullet.cpp \
		ceilwall.cpp \
		chopper.cpp \
		doubler.cpp \
		enemy.cpp \
		floatwall.cpp \
		game.cpp \
		item.cpp \
		life.cpp \
		main.cpp \
		obstacle.cpp moc_game.cpp
OBJECTS       = bomb.o \
		bounds.o \
		bullet.o \
		ceilwall.o \
		chopper.o \
		doubler.o \
		enemy.o \
		floatwall.o \
		game.o \
		item.o \
		life.o \
		main.o \
		obstacle.o \
		moc_game.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hw4.pro
QMAKE_TARGET  = hw4
DESTDIR       = 
TARGET        = hw4

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hw4.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile hw4.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile hw4.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hw41.0.0 || $(MKDIR) .tmp/hw41.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hw41.0.0/ && $(COPY_FILE) --parents bomb.h bounds.h bullet.h ceilwall.h chopper.h doubler.h enemy.h floatwall.h game.h item.h life.h obstacle.h .tmp/hw41.0.0/ && $(COPY_FILE) --parents bomb.cpp bounds.cpp bullet.cpp ceilwall.cpp chopper.cpp doubler.cpp enemy.cpp floatwall.cpp game.cpp item.cpp life.cpp main.cpp obstacle.cpp .tmp/hw41.0.0/ && (cd `dirname .tmp/hw41.0.0` && $(TAR) hw41.0.0.tar hw41.0.0 && $(COMPRESS) hw41.0.0.tar) && $(MOVE) `dirname .tmp/hw41.0.0`/hw41.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hw41.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_game.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_game.cpp
moc_game.cpp: chopper.h \
		floatwall.h \
		obstacle.h \
		bullet.h \
		enemy.h \
		life.h \
		item.h \
		bomb.h \
		doubler.h \
		ceilwall.h \
		game.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game.h -o moc_game.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

bomb.o: bomb.cpp bomb.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bomb.o bomb.cpp

bounds.o: bounds.cpp bounds.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bounds.o bounds.cpp

bullet.o: bullet.cpp bullet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bullet.o bullet.cpp

ceilwall.o: ceilwall.cpp ceilwall.h \
		obstacle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ceilwall.o ceilwall.cpp

chopper.o: chopper.cpp chopper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chopper.o chopper.cpp

doubler.o: doubler.cpp doubler.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doubler.o doubler.cpp

enemy.o: enemy.cpp enemy.h \
		obstacle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enemy.o enemy.cpp

floatwall.o: floatwall.cpp floatwall.h \
		obstacle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o floatwall.o floatwall.cpp

game.o: game.cpp game.h \
		chopper.h \
		floatwall.h \
		obstacle.h \
		bullet.h \
		enemy.h \
		life.h \
		item.h \
		bomb.h \
		doubler.h \
		ceilwall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

item.o: item.cpp item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o item.cpp

life.o: life.cpp life.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o life.o life.cpp

main.o: main.cpp game.h \
		chopper.h \
		floatwall.h \
		obstacle.h \
		bullet.h \
		enemy.h \
		life.h \
		item.h \
		bomb.h \
		doubler.h \
		ceilwall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

obstacle.o: obstacle.cpp obstacle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obstacle.o obstacle.cpp

moc_game.o: moc_game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_game.o moc_game.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

